---
- name: Tarea para crear archivo /tmp/alumno/datos.txt
  ansible.builtin.file:
    path: /tmp/alumno
    state: directory
    mode: 0755  # Ajusta los permisos según sea necesario

- name: Crear archivo /tmp/alumno/datos.txt
  ansible.builtin.copy:
    content: |
      Nombre: Gonzalo
      Apellido: Brito
      División: C311
      Fecha: {{ ansible_date_time.date }}
      ---
      Distribución: {{ ansible_distribution }}
      Cantidad de Cores: {{ ansible_processor_cores }}
    dest: /tmp/alumno/datos.txt
