---
# tasks file for Instala-tools_Brito


- name: Instalar htop, tmux, tree y speedtest-cli
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - htop
    - tmux
    - tree
    - speedtest-cli
  become: yes
